// Generated by scripts/subset-web-fonts.py. Preload only for Japanese pages.
export const japaneseBodyFonts = [
  '/fonts/NotoSansJP-critical400-244c9c212034.woff2',
  '/fonts/NotoSansJP-critical500-a8a9650bca36.woff2',
] as const;
