// Generated by scripts/subset-web-fonts.py. Preload only for Japanese pages.
export const japaneseBodyFonts = [
  '/fonts/NotoSansJP-critical400-a7465d257bcd.woff2',
  '/fonts/NotoSansJP-critical500-cce5a5b4e09f.woff2',
] as const;
