// @generated by scripts/tasks/sync-auth-email-templates.ts
// Source of truth: supabase/functions/send-auth-email/. Do not edit this file directly.

/**
 * Auth メール件名の en/ja 辞書
 *
 * index.ts（送信時の subject）が正本として参照する。
 * Storybook プレビューは pnpm auth-email:sync が生成する
 * apps/product/src/emails/auth-email-subjects.generated.ts 経由で同じ辞書を表示する。
 */

export type AuthEmailLocale = 'en' | 'ja';

export type AuthEmailSubjectKey =
  | 'signup'
  | 'recovery'
  | 'magic_link'
  | 'email_change_current'
  | 'email_change_new'
  | 'password_changed_notification';

export const authEmailSubjects: Record<AuthEmailLocale, Record<AuthEmailSubjectKey, string>> = {
  en: {
    signup: 'Confirm your Dayopt email',
    recovery: 'Reset your Dayopt password',
    magic_link: 'Log in to Dayopt',
    email_change_current: 'Approve your Dayopt email change',
    email_change_new: 'Confirm your new Dayopt email',
    password_changed_notification: 'Your Dayopt password was changed',
  },
  ja: {
    signup: 'Dayopt メールアドレスの確認',
    recovery: 'Dayopt パスワードのリセット',
    magic_link: 'Dayopt にログイン',
    email_change_current: 'Dayopt メールアドレス変更の承認',
    email_change_new: 'Dayopt 新しいメールアドレスの確認',
    password_changed_notification: 'Dayopt パスワードが変更されました',
  },
};
