// @generated by scripts/tasks/sync-auth-email-templates.ts
// Source of truth: supabase/functions/send-auth-email/. Do not edit this file directly.

/**
 * Magic Link Email Template
 * マジックリンクログイン時のメール
 *
 * Supabase Auth の magic_link フローで使用
 */

import { Body, Button, Container, Head, Html, Link, Section, Text } from 'react-email';

import * as styles from './auth-email-styles.generated';

type Locale = 'en' | 'ja';

const i18n = {
  en: {
    heading: 'Log in to Dayopt',
    body: 'Click the button below to log in to your Dayopt account. No password needed.',
    ctaButton: 'Log In to Dayopt',
    buttonFallback: "If the button doesn't work, copy and paste this link into your browser:",
    expiryNote: 'This link expires. If it has expired, request a new link.',
    ignoreLine:
      "If you didn't request this login link, you can safely ignore this email. Someone may have entered your email address by mistake.",
    teamSignature: 'The Dayopt Team',
  },
  ja: {
    heading: 'Dayopt にログイン',
    body: '以下のボタンをクリックして、Dayopt アカウントにログインしてください。パスワードは不要です。',
    ctaButton: 'Dayopt にログイン',
    buttonFallback:
      'ボタンが機能しない場合は、以下のリンクをブラウザにコピー＆ペーストしてください：',
    expiryNote:
      'このリンクには有効期限があります。期限が切れた場合は、再度リンクをリクエストしてください。',
    ignoreLine:
      'ログインリンクをリクエストした覚えがない場合は、このメールを無視してください。他の方がメールアドレスを間違えて入力した可能性があります。',
    teamSignature: 'Dayopt チーム',
  },
} as const;

export interface MagicLinkEmailProps {
  loginUrl: string;
  locale?: Locale;
  appUrl?: string;
}

export function MagicLinkEmail({
  loginUrl,
  locale = 'en',
  appUrl = 'https://app.dayopt.app',
}: MagicLinkEmailProps) {
  const t = i18n[locale];
  return (
    <Html>
      <Head />
      <Body style={styles.main}>
        <Container style={styles.container}>
          <Section style={styles.section}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.paragraph}>{t.body}</Text>
            <Button style={styles.button} href={loginUrl}>
              {t.ctaButton}
            </Button>
            <Text style={styles.smallText}>{t.buttonFallback}</Text>
            <Text style={{ ...styles.smallText, wordBreak: 'break-all' }}>
              <Link style={styles.link} href={loginUrl}>
                {loginUrl}
              </Link>
            </Text>
            <Text style={styles.smallText}>{t.expiryNote}</Text>
            <Text style={styles.footer}>
              {t.ignoreLine}
              <br />
              <br />
              <Link style={styles.link} href={appUrl}>
                app.dayopt.app
              </Link>
              <br />
              <br />
              {t.teamSignature}
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export default MagicLinkEmail;
