/**
 * OG fallback画像(静的PNG)の生成スクリプト
 *
 * `apps/web/src/app/api/og/route.tsx` の fallback応答は
 * global quota超過時・rate limit backend障害時に Satori の compute cost を
 * 発生させ続けないよう、同じ `@dayopt/assets` renderer を**一度だけ**
 * Satoriでレンダリングし、結果を2箇所に出力する:
 *
 * 1. `public/og-fallback.png` — PRで目視レビューできる実体
 * 2. `src/app/api/og/og-fallback-image.generated.ts` — 同じbyte列をbase64定数として
 *    route.tsxへ埋め込み、fallback 時の追加 I/O や画像レンダリングを避ける
 *
 * デザインを変更する場合は共通 renderer を更新し、再実行して出力を再生成する。
 *
 * 使用方法: pnpm --filter @dayopt/web generate:og-fallback
 */

import { OG_CARD_SIZE } from '@dayopt/assets/og';
import { OgCardImage } from '@dayopt/assets/og-card-image';
import { loadOgFonts } from '@dayopt/assets/og-fonts';
import { ImageResponse } from 'next/og';
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const PNG_OUTPUT_PATH = path.join(process.cwd(), 'public', 'og-fallback.png');
const MODULE_OUTPUT_PATH = path.join(
  process.cwd(),
  'src/app/api/og/og-fallback-image.generated.ts',
);

async function main() {
  const response = new ImageResponse(
    <OgCardImage
      title="Plan your day. Track your time. Optimize your life."
      category="product"
      categoryLabel="Product"
      layout="left"
    />,
    { ...OG_CARD_SIZE, fonts: await loadOgFonts() },
  );

  const buffer = Buffer.from(await response.arrayBuffer());
  writeFileSync(PNG_OUTPUT_PATH, buffer);
  console.log(`wrote ${buffer.byteLength} bytes to ${PNG_OUTPUT_PATH}`);

  const moduleSource = `// AUTO-GENERATED by \`pnpm --filter @dayopt/web generate:og-fallback\`. Do not edit by hand.
// 元データ: apps/web/public/og-fallback.png (1200x630 Light OGP fallback)。
// route.tsx はこのbase64定数を直接使い、fallback時の再レンダリングを避ける。
export const OG_FALLBACK_IMAGE_BASE64 = '${buffer.toString('base64')}';
`;
  writeFileSync(MODULE_OUTPUT_PATH, moduleSource);
  console.log(`wrote ${moduleSource.length} chars to ${MODULE_OUTPUT_PATH}`);

  // 生ファイル書き込みはprettier未適用のため、format:checkとの差分を残さないよう
  // 生成直後にformatする(手動フォローアップをこのscriptの責務にする)。
  execFileSync('pnpm', ['exec', 'prettier', '--write', MODULE_OUTPUT_PATH], {
    stdio: 'inherit',
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
