-- ============================================================
-- 関数一覧（読み物用 — CLIでは使用しない）
-- ============================================================
-- 最終同期日: 2026-08-10
-- 同期対象 migration:
--   - 20260415000000_inline_entry_tag_id.sql
--   - 20260424000000_restore_tag_parent_hierarchy.sql
--   - 20260425130000_merge_tags_with_hierarchy_auth_guard.sql
--   - 20260514000918_mcp_phase_1_5.sql
--   - 20260604230607_harden_function_execute_privileges.sql
--   - 20260610000000_entry_auto_record_model.sql
--   - 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   - 20260615000000_drop_unused_stats_rpcs.sql
--   - 20260616000000_rename_duration_to_planned_duration.sql
--   - 20260712212527_records_table_and_drop_entries.sql
--   - 20260713120023_drop_time_model_compatibility_layer.sql
--   - 20260729062428_mcp_oauth_connections_expand.sql
--   - 20260729062430_oauth_refresh_rotation_hardening.sql
--   - 20260729062433_oauth_connection_cutover_hardening.sql
--   - 20260729062435_timeblock_atomic_commands.sql
--   - 20260729062437_timeblock_command_hardening.sql
--   - 20260729062439_timeblock_confirm_day_command.sql
--   - 20260729062441_timeblock_confirm_day_serialization.sql
--   - 20260729062443_timeblock_confirm_day_range_limit.sql
--   - 20260729062445_mcp_mutation_envelope_foundation.sql
--   - 20260729062447_allow_mcp_receipt_connection_detach.sql
--   - 20260729062449_mcp_plan_create_apply.sql
--   - 20260729062451_fix_mcp_plan_create_helper_casts.sql
--   - 20260729062453_mcp_plan_mutations_apply.sql
--   - 20260729062456_recheck_mcp_plan_create_authority.sql
--   - 20260729062458_recordable_plan_error_contract.sql
--   - 20260729062500_recordable_plan_trigger_error_contract.sql
--   - 20260729062502_mcp_record_mutations_apply.sql
--   - 20260729073122_mcp_stage1_user_write_serialization.sql
--   - 20260729073123_mcp_stage1_legacy_writer_compatibility.sql
--   - 20260729073124_mcp_stage1_revision_fence.sql
--   - 20260729073125_mcp_environment_identity_client_fence.sql
--   - 20260729073126_mcp_stage1_receipt_generation_lifecycle.sql
--   - 20260729073127_legacy_linked_record_restore_compatibility.sql
--   - 20260730090301_harden_authenticated_timeblock_write_boundary.sql
--   - 20260802013954_add_product_events.sql
--   - 20260810013820_observe_legacy_oauth_bind.sql
--   - 20260810041210_drop_lock_timeblock_global_write_shim.sql
--   - 20260810070002_add_oauth_retention_cleanup_rpcs.sql
--   - 20260810085241_bound_oauth_connection_cleanup_cascade.sql
-- Browser-facing 関数は authenticated、DB owner の command / OAuth / MCP apply は
-- service_role にだけ明示 GRANT。PUBLIC/anon への EXECUTE は revoke 済み。
-- ============================================================

-- ■ トリガー関数
--   update_updated_at()                       — 汎用 updated_at 自動更新
--   handle_new_user()                         — auth.users INSERT → profiles 自動作成
--   private.track_product_user_signup_v1()    — auth.users INSERT → payload-free signup event
--   bind_legacy_oauth_insert_to_connection()  — oauth codes/tokens の connection_id NULL insert を
--       legacy connection へ補完する互換 trigger（WHEN 句で NULL 時のみ発火、SECURITY DEFINER）。
--       20260810013820 で補完実行を private.legacy_oauth_bind_observations へ append-only 記録する
--       観測 INSERT を追加（候補8 Stage 8-3 の停止条件。現行定義の正本は 20260810013820）。
--       Stage 8-3 の forward restoration は観測 INSERT の無い 20260729073125 の定義へ戻す
-- ■ RPC 関数
--   update_personalization(user_id, key, value) — user_settings.personalization 更新
--   use_recovery_code(user_id, code_hash)     — MFAリカバリーコードを使用済みにマーク
--   count_unused_recovery_codes(user_id)      — 未使用リカバリーコード数
--   soft_delete_plan / restore_plan            — Plan の soft delete / restore
--   soft_delete_record / restore_record        — Record の soft delete / restore
--   confirm_day_plans_to_records(...)          — 完了 Plan を Record として一括確定
--     ↑ soft_delete_plan / soft_delete_record / confirm_day_plans_to_records の 3 つは
--       **drain まで authenticated に残す互換 wrapper**。SECURITY DEFINER で、内部は
--       private.*_unserialized_v1 へ委譲する (20260729073123)。Candidate 6 で
--       plans / records の直接 DML を剥がした後、旧 bundle に残る唯一の write 経路。
--       旧 instance の drain 完了後に EXECUTE を revoke する
--       （20260730090300 / 20260730090301 は EXECUTE が残っていることを assert する
--       ので、drain migration では assertion も反転させる）。
--
--       **owner 境界は caller 依存**。「常に auth.uid() 照合される」と読まないこと。
--       3 関数は `auth.jwt() ->> 'role'` で分岐する:
--         - browser session caller (authenticated): p_user_id が auth.uid() と
--           一致しなければ 42501。JWT が境界。
--         - service_role caller: auth.uid() 照合を skip し、p_user_id 自体が境界。
--           tRPC の oauth / service-role auth mode はどちらも ctx.supabase に
--           service-role client を入れる (apps/product/src/lib/trpc/context.ts) ため、
--           app 側が ctx.userId を渡し続けることが前提になる
--           （docs/engineering/invariants.md の不変条件）
--       restore_plan / restore_record は service_role のみ（authenticated は revoke 済み）
--   issue_oauth_token_pair(...)               — refresh/access token pair を service-role 経由で発行
--   create_oauth_authorization_grant_v2(...)   — connection-bound code を発行（service-role only）
--   exchange_oauth_authorization_code_v2(...)  — code を一度だけ token family へ交換（service-role only）
--   rotate_oauth_refresh_token_v2(...)         — rotation / reuse 検知（service-role only）
--   revoke_oauth_connection(...)               — connection と token family を失効
--   get_mcp_environment_identity_v1()          — DB-owned authority identity取得（service-role only）
--   provision_mcp_preview_environment_identity_v1(...)
--     — data-less PR PreviewのURL/project-ref/JWT-refをinsert-onceで固定
--   create/update/delete/restore_plan_command_v1(...)
--   set_plan_skipped_command_v1(...)           — 旧clientへ撤去案内を返す互換stub
--   create/update/delete/restore_record_command_v1(...)
--   record_plan_command_v1(...)
--   confirm_day_plans_command_v1(...)
--     — Plan / Record の原子的 command。service-role only
--   get_timeblock_context_marker_v1(...)       — user単位revision/DB時刻/timezone
--   set_mcp_mutation_control_v1(...)           — revision CAS 付き global gate（service-role only）
--   set_mcp_client_write_control_v1(...)       — revision CAS 付き client gate（service-role only）
--   get_user_data_generation_v1(...)           — account-preserving purge世代（service-role only）
--   apply_mcp_plan_create/update/delete/restore_v1(...)
--   apply_mcp_record_create/update/delete/restore_v1(...)
--     — authority再検証、domain write、receipt作成を同一transactionで行う（service-role only）
--   cleanup_oauth_authorization_codes_v1(...)  — 24時間超authorization codeのbounded cleanup（service-role only）
--   cleanup_oauth_access_tokens_v1(...)        — 24時間超access tokenのbounded cleanup（service-role only）
--   cleanup_oauth_refresh_tokens_v1(...)       — 30日超refresh tokenのbounded cleanup（service-role only）
--   cleanup_oauth_connections_v1(...)          — 90日超connectionのbounded cleanup。残存token/codeを
--       持つ親は候補から外し（cascadeを無制限に走らせない）、
--       mcp_mutation_receipts.origin_connection_idをdetach（service-role only）
--   cleanup_mcp_mutation_receipts_v1(...)      — 90日超receiptのbounded cleanup（service-role only）
--   save_calendar_connection_command_v1(...)   — purge世代を再検証してCalendar接続を保存
--   rotate_or_enqueue_calendar_refresh_token_command_v2(...)
--     — token rotationを冪等保存し、purge後はrevoke outboxへ退避
--   prepare_user_data_purge_v1(...) / delete_all_user_data_command_v5(...)
--     — DB発行operationとgenerationで再送安全な全データ削除を行う
--   claim/complete/retry/expire_calendar_revoke_outbox_v1(...)
--     — 暗号化tokenをlease付きで失効し、24時間以内に必ず破棄する
--   provision/get_calendar_authority_*_v1(...) — Google project identityとauthority状態を管理
--   begin/prepare/start/finalize/seal_calendar_account_*_v1(...)
--     — account削除前にCalendar provider結果をdurableに確定する
--   begin/claim/complete/seal_account_deletion_v1(...)
--     — Calendar / Storage / Billingの削除stepを再開可能に管理する
--   claim/start/reconcile_billing_mutation_v2/v3/v4(...)
--     — Checkout / Portalを同じ意図の再送で二重作成しない
--   claim/start/complete_billing_customer_provisioning_v2(...)
--     — Stripe Customer作成とaccount削除を直列化する
--   sync_billing_subscription_deleted_v1(...) — liveまたは削除済みCustomerを終端する
--   classify_billing_customer_event_v1(...)   — live / account_deleted / unknownを区別する
--   cleanup_billing_mutation_claims_v2(...)   — 期限切れredirect URLとterminal claimを削除する
--   cleanup_billing_account_deletion_terminal_receipts_v2(...)
--     — 30日経過したCustomer digest receiptを削除する
--   cleanup_integration_security_events_v1(...) — payload-free eventを90日で削除する
--   get_external_authority_maintenance_status_v1() — IDを含まないbacklog集計
--   get_external_lifecycle_app_version_v2() — Candidate 3 terminal schema marker
--   private.cleanup_product_events_v1(...) — 90日超eventのbounded cleanup（DB owner only）

-- ■ private schema（Data API 非公開）
--   authorize_mcp_mutation_v1(...)             — environment/global/client/user/connection/
--                                                 token/scope/期限/Proを同一writer fence内で再検証
--   digest_mcp_mutation_envelope_v1(...)       — typed args のcanonical digest
--   lock_mcp_mutation_operation_v1(...)        — user/client/operation単位のadvisory lock
--   lock_timeblock_user_write_shared/exclusive_v1(...)
--                                               — user単位writer lockとrevision row lock
--   bind_timeblock_supported_writer_lock_v1(...) — user/mode bindingとlock upgrade拒否
--   resolve_mcp_mutation_replay_v1(...)        — digest/resource/generation replay判定
--   enforce_mcp_mutation_receipt_lifecycle_v1() — receipt immutable / DB-authored generation
--   get/require_mcp_environment_resource_v1(...) — DB identity先行resource fence

-- ■ 削除済み RPC
--   get_tag_cumulative_time / get_tag_avg_fulfillment / get_tag_plan_rate /
--   get_tag_fulfillment_distribution / get_tag_hourly_distribution /
--   get_tag_dow_distribution / get_child_tag_breakdown /
--   get_tag_accuracy_trend / get_tag_recent_entries
--     -> 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   get_energy_map / get_context_switches / get_cumulative_time /
--   get_plan_rate / get_avg_fulfillment
--     -> 20260615000000_drop_unused_stats_rpcs.sql
--   entries 系 CRUD / stats / backfill RPC
--     -> 20260712212527_records_table_and_drop_entries.sql
--   soft_delete_log / restore_log / confirm_day_plans_to_logs
--     -> 20260713120023_drop_time_model_compatibility_layer.sql
