/**
 * Inventory（事実）+ 用語集（意味）+ Feature DAG（依存）→ LikeC4 model / views の生成。
 *
 * LikeC4 側には手書きの事実を置かない。要素・関係・metadata・link はすべてここで生成し、
 * 人間が書くのは（必要になれば）追加の view だけ。生成物は `docs/engineering/data/architecture/` に置き、
 * `likec4 validate` が構文を、`pnpm architecture:check` が drift を止める。
 *
 * 要素の命名: 種別 prefix + 識別子（`c_plan` / `f_timeblock` / `t_plans` / `fn_x` / `r_plans` /
 * `mcp_plans_create` / `s_useXStore`）。table と feature に同名（activities）があるため prefix で衝突を避ける。
 */

import type { GlossaryEntry } from '../glossary/core.ts';
import type { CallGraph } from './call-graph.ts';
import type { ConceptMap, MappedItem } from './concept-map.ts';
import { conceptAnchor } from './concept-navigation.ts';
import type { FeatureDag } from './feature-dag.ts';
import type { InventoryKind } from './inventory.ts';
import type { Relations } from './relations.ts';
import type { SchemaModel } from './schema-model.ts';
import type { SystemSurface } from './surface.ts';
import { vocabularyExclusionReason } from './vocabulary-scope.ts';

const KIND_PREFIX: Partial<Record<InventoryKind, string>> = {
  feature: 'f',
  table: 't',
  'db-function': 'fn',
  'trpc-router': 'r',
  'mcp-tool': 'mcp',
  store: 's',
};

/** LikeC4 の識別子（英数字 / _ / - のみ、先頭は英字か _）へ寄せる。 */
export function likec4Id(prefix: string, id: string): string {
  return `${prefix}_${id.replace(/[^A-Za-z0-9_-]/g, '_')}`;
}

function quote(text: string): string {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function conceptId(entry: GlossaryEntry): string {
  return likec4Id('c', entry.id);
}

function itemId(item: MappedItem): string | undefined {
  const prefix = KIND_PREFIX[item.kind];
  return prefix === undefined ? undefined : likec4Id(prefix, item.id);
}

function isDirect(item: MappedItem, concept: string): boolean {
  return item.links.some((link) => link.conceptId === concept && link.via === 'direct');
}

export interface LikeC4Sources {
  map: ConceptMap;
  glossary: readonly GlossaryEntry[];
  dag: FeatureDag;
  schema: SchemaModel;
  surface: SystemSurface;
  relations: Relations;
  callGraph: CallGraph;
}

/** model file（docs/engineering/data/architecture/）から repo root へ戻る相対 prefix */
const REPO_ROOT_PREFIX = '../../../../';

const HEADER = [
  '// generated by scripts/tasks/generate-architecture-map.ts (pnpm architecture:generate)',
  '// 手で編集しない。正本は実装（Inventory）/ scripts/lib/glossary/terms.ts / eslint.config.mjs。',
  '// 検証: pnpm architecture:check（drift）と likec4 validate（構文）',
  '',
];

export function renderLikeC4Model({
  map,
  glossary,
  dag,
  schema,
  surface,
  relations,
  callGraph,
}: LikeC4Sources): string {
  const out = [...HEADER];
  out.push('specification {');
  out.push('  element concept { style { shape rectangle; color primary } }');
  out.push('  element feature { style { color secondary } }');
  out.push('  element table { style { shape storage; color muted } }');
  out.push('  element dbfunction { style { shape queue; color muted } }');
  out.push('  element router { style { color muted } }');
  out.push('  element mcptool { style { shape browser; color muted } }');
  out.push('  element store { style { color muted } }');
  out.push('  element httproute { style { shape browser; color secondary } }');
  out.push('  element schedule { style { shape queue; color secondary } }');
  out.push('  tag unmapped');
  out.push('}');
  out.push('');

  out.push('model {');

  // 概念（対応を 1 つでも持つものだけ）
  const usedConcepts = glossary.filter((entry) => (map.byConcept.get(entry.id) ?? []).length > 0);
  for (const entry of usedConcepts) {
    out.push(`  concept ${conceptId(entry)} ${quote(entry.concept)} {`);
    out.push(`    description ${quote(entry.usage)}`);
    out.push(`    metadata { glossary ${quote(entry.id)} layer ${quote(entry.layer)} }`);
    out.push(`    link ${REPO_ROOT_PREFIX}scripts/lib/glossary/terms.ts`);
    out.push(
      `    link https://github.com/Dayopt/dayopt/blob/main/docs/engineering/data/architecture-inventory.md#${conceptAnchor(entry.id)} '関連候補（main）'`,
    );
    out.push('  }');
  }

  // Inventory の要素（model に載せる種別だけ）
  const modelItems = map.items.filter((item) => KIND_PREFIX[item.kind] !== undefined);
  for (const item of modelItems) {
    const id = itemId(item);
    if (id === undefined) continue;
    const kind =
      item.kind === 'db-function'
        ? 'dbfunction'
        : item.kind === 'trpc-router'
          ? 'router'
          : item.kind === 'mcp-tool'
            ? 'mcptool'
            : item.kind;
    out.push(`  ${kind} ${id} ${quote(item.id)} {`);
    // 語彙を持たないことが正しい要素（SQL 内部・認証の定型画面など）は #unmapped を付けない。
    // 全部に付けると view が数百要素になり、判断すべき要素が読めなくなる。
    if (item.links.length === 0 && vocabularyExclusionReason(item) === undefined) {
      out.push('    #unmapped');
    }
    // `kind` は LikeC4 の予約語（where kind is ...）なので metadata のキーに使えない
    const meta = [`inventoryKind ${quote(item.kind)}`];
    if (item.feature) meta.push(`feature ${quote(item.feature)}`);
    if (item.detail) meta.push(`detail ${quote(item.detail)}`);
    out.push(`    metadata { ${meta.join(' ')} }`);
    out.push(`    link ${REPO_ROOT_PREFIX}${item.path}`);
    out.push('  }');
  }
  // HTTP route と定期実行（概念を持たない運用面。link から実装へ飛べる）
  for (const route of surface.httpRoutes) {
    out.push(`  httproute ${likec4Id('h', `${route.app}${route.id}`)} ${quote(route.id)} {`);
    out.push(
      `    metadata { app ${quote(route.app)} methods ${quote(route.methods.join(', ') || 'none')} }`,
    );
    out.push(`    link ${REPO_ROOT_PREFIX}${route.path}`);
    out.push('  }');
  }
  for (const job of surface.schedules) {
    out.push(`  schedule ${likec4Id('cron', `${job.source}_${job.id}`)} ${quote(job.id)} {`);
    out.push(
      `    metadata { source ${quote(job.source)} schedule ${quote(job.schedule)} authoritative ${quote(String(job.authoritative))} }`,
    );
    out.push(`    link ${REPO_ROOT_PREFIX}${job.path}`);
    out.push('  }');
  }
  out.push('');

  // 定期実行 → HTTP route（Vercel cron は route を叩く）
  for (const job of surface.schedules) {
    const route = surface.httpRoutes.find(
      (candidate) => candidate.app === 'product' && candidate.id === job.target,
    );
    if (route === undefined) continue;
    out.push(
      `  ${likec4Id('cron', `${job.source}_${job.id}`)} -> ${likec4Id('h', `${route.app}${route.id}`)} 'triggers'`,
    );
  }

  // 概念 → 直接対応
  for (const entry of usedConcepts) {
    for (const item of map.byConcept.get(entry.id) ?? []) {
      const id = itemId(item);
      if (id === undefined || !isDirect(item, entry.id)) continue;
      out.push(`  ${conceptId(entry)} -> ${id} 'direct'`);
    }
  }
  // feature → feature（実 import）
  for (const edge of dag.edges) {
    out.push(`  ${likec4Id('f', edge.from)} -> ${likec4Id('f', edge.to)} 'imports'`);
  }
  // feature → router / store（所属）、feature → 関数（.rpc 呼び元）
  for (const item of modelItems) {
    const id = itemId(item);
    if (id === undefined) continue;
    if ((item.kind === 'trpc-router' || item.kind === 'store') && item.feature) {
      out.push(`  ${likec4Id('f', item.feature)} -> ${id} 'owns'`);
    }
    if (item.kind === 'db-function') {
      for (const feature of item.usedBy ?? []) {
        if (dag.features.includes(feature)) {
          out.push(`  ${likec4Id('f', feature)} -> ${id} 'calls'`);
        }
      }
    }
  }
  // feature → table（`.from()` の呼び元）
  for (const item of modelItems) {
    if (item.kind !== 'table') continue;
    const id = itemId(item);
    if (id === undefined) continue;
    for (const feature of item.usedBy ?? []) {
      if (dag.features.includes(feature)) out.push(`  ${likec4Id('f', feature)} -> ${id} 'reads'`);
    }
  }
  // MCP tool → tRPC router（tool file が呼ぶ procedure の namespace）
  const routerIds = new Set(
    map.items.filter((item) => item.kind === 'trpc-router').map((item) => item.id),
  );
  for (const entry of relations.mcpToolProcedures) {
    const namespaces = new Set(entry.procedures.map((procedure) => procedure.split('.')[0]));
    for (const tool of entry.tools) {
      for (const namespace of namespaces) {
        if (routerIds.has(namespace)) {
          out.push(`  ${likec4Id('mcp', tool)} -> ${likec4Id('r', namespace)} 'calls'`);
        }
      }
    }
  }
  // tRPC router → テーブル / DB 関数（型チェッカーで辿った procedure の集約）
  const routerReads = new Map<string, Set<string>>();
  const routerCalls = new Map<string, Set<string>>();
  for (const procedure of callGraph.procedures) {
    const namespace = procedure.id.split('.')[0];
    if (!routerIds.has(namespace)) continue;
    for (const [target, bucket] of [
      [procedure.tables, routerReads],
      [procedure.functions, routerCalls],
    ] as const) {
      let set = bucket.get(namespace);
      if (set === undefined) {
        set = new Set();
        bucket.set(namespace, set);
      }
      for (const name of target) set.add(name);
    }
  }
  const tableElementIds = new Set(
    map.items.filter((item) => item.kind === 'table').map((item) => item.id),
  );
  const functionElementIds = new Set(
    map.items.filter((item) => item.kind === 'db-function').map((item) => item.id),
  );
  for (const [namespace, tables] of routerReads) {
    for (const table of [...tables].sort()) {
      if (tableElementIds.has(table)) {
        out.push(`  ${likec4Id('r', namespace)} -> ${likec4Id('t', table)} 'reads'`);
      }
    }
  }
  for (const [namespace, functions] of routerCalls) {
    for (const fn of [...functions].sort()) {
      if (functionElementIds.has(fn)) {
        out.push(`  ${likec4Id('r', namespace)} -> ${likec4Id('fn', fn)} 'calls'`);
      }
    }
  }
  // table → table（FK）
  const tableIds = new Set(schema.tables.map((table) => likec4Id('t', table.name)));
  for (const table of schema.tables) {
    for (const relationship of table.relationships) {
      const target = likec4Id('t', relationship.referencedTable);
      // 自己参照 FK（oauth_tokens.parent_token_id）は LikeC4 が relation として受け付けない
      if (!tableIds.has(target) || target === likec4Id('t', table.name)) continue;
      out.push(
        `  ${likec4Id('t', table.name)} -> ${target} ${quote(`FK ${relationship.columns.join(', ')}`)}`,
      );
    }
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}

export function renderLikeC4Views({ map, glossary }: LikeC4Sources): string {
  const out = [...HEADER];
  out.push('views {');
  out.push('  view index {');
  out.push("    title 'Dayopt Architecture Map'");
  out.push("    description '概念と feature。概念を選ぶと対応する実装の view へ辿れる'");
  out.push('    include * where kind is concept');
  out.push('    include * where kind is feature');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view features {');
  out.push("    title 'Feature DAG（実 import）'");
  out.push('    include * where kind is feature');
  out.push('    autoLayout TopBottom');
  out.push('  }');
  out.push('  view data {');
  out.push("    title 'DB テーブルと FK'");
  out.push('    include * where kind is table');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view mcp {');
  out.push("    title 'MCP tool と概念'");
  out.push('    include * where kind is mcptool');
  out.push('    include * where kind is concept');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view api {');
  out.push("    title 'HTTP route と定期実行'");
  out.push('    include * where kind is httproute');
  out.push('    include * where kind is schedule');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view unmapped {');
  out.push("    title '概念を足す候補（語彙を持たない層は除く）'");
  out.push('    include * where tag is #unmapped');
  out.push('    autoLayout TopBottom');
  out.push('  }');
  for (const entry of glossary) {
    const items = map.byConcept.get(entry.id) ?? [];
    if (!items.some((item) => isDirect(item, entry.id) && itemId(item) !== undefined)) continue;
    const id = conceptId(entry);
    out.push(`  view concept_${entry.id.replace(/-/g, '_')} of ${id} {`);
    out.push(`    title ${quote(`${entry.concept}（${entry.id}）`)}`);
    out.push(`    include ${id}, ${id} ->`);
    out.push('    autoLayout LeftRight');
    out.push('  }');
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}
