/**
 * Inventory（事実）+ 用語集（意味）+ Feature DAG（依存）→ LikeC4 model / views の生成。
 *
 * LikeC4 側には手書きの事実を置かない。要素・関係・metadata・link はすべてここで生成し、
 * 人間が書くのは（必要になれば）追加の view だけ。生成物は `architecture/` 配下に置き、
 * `likec4 validate` が構文を、`pnpm architecture:check` が drift を止める。
 *
 * 要素の命名: 種別 prefix + 識別子（`c_plan` / `f_timeblock` / `t_plans` / `fn_x` / `r_plans` /
 * `mcp_plans_create` / `s_useXStore`）。table と feature に同名（activities）があるため prefix で衝突を避ける。
 */

import type { GlossaryEntry } from '../glossary/core.ts';
import type { ConceptMap, MappedItem } from './concept-map.ts';
import type { FeatureDag } from './feature-dag.ts';
import type { InventoryKind } from './inventory.ts';
import type { SchemaModel } from './schema-model.ts';

const KIND_PREFIX: Partial<Record<InventoryKind, string>> = {
  feature: 'f',
  table: 't',
  'db-function': 'fn',
  'trpc-router': 'r',
  'mcp-tool': 'mcp',
  store: 's',
};

/** LikeC4 の識別子（英数字 / _ / - のみ、先頭は英字か _）へ寄せる。 */
export function likec4Id(prefix: string, id: string): string {
  return `${prefix}_${id.replace(/[^A-Za-z0-9_-]/g, '_')}`;
}

function quote(text: string): string {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function conceptId(entry: GlossaryEntry): string {
  return likec4Id('c', entry.id);
}

function itemId(item: MappedItem): string | undefined {
  const prefix = KIND_PREFIX[item.kind];
  return prefix === undefined ? undefined : likec4Id(prefix, item.id);
}

function isDirect(item: MappedItem, concept: string): boolean {
  return item.links.some((link) => link.conceptId === concept && link.via === 'direct');
}

export interface LikeC4Sources {
  map: ConceptMap;
  glossary: readonly GlossaryEntry[];
  dag: FeatureDag;
  schema: SchemaModel;
}

const HEADER = [
  '// generated by scripts/tasks/generate-architecture-map.ts (pnpm architecture:generate)',
  '// 手で編集しない。正本は実装（Inventory）/ scripts/lib/glossary/terms.ts / eslint.config.mjs。',
  '// 検証: pnpm architecture:check（drift）と likec4 validate（構文）',
  '',
];

export function renderLikeC4Model({ map, glossary, dag, schema }: LikeC4Sources): string {
  const out = [...HEADER];
  out.push('specification {');
  out.push('  element concept { style { shape rectangle; color primary } }');
  out.push('  element feature { style { color secondary } }');
  out.push('  element table { style { shape storage; color muted } }');
  out.push('  element dbfunction { style { shape queue; color muted } }');
  out.push('  element router { style { color muted } }');
  out.push('  element mcptool { style { shape browser; color muted } }');
  out.push('  element store { style { color muted } }');
  out.push('  tag unmapped');
  out.push('}');
  out.push('');

  out.push('model {');

  // 概念（対応を 1 つでも持つものだけ）
  const usedConcepts = glossary.filter((entry) => (map.byConcept.get(entry.id) ?? []).length > 0);
  for (const entry of usedConcepts) {
    out.push(`  concept ${conceptId(entry)} ${quote(entry.concept)} {`);
    out.push(`    description ${quote(entry.usage)}`);
    out.push(`    metadata { glossary ${quote(entry.id)} layer ${quote(entry.layer)} }`);
    out.push('    link ../scripts/lib/glossary/terms.ts');
    out.push('  }');
  }

  // Inventory の要素（model に載せる種別だけ）
  const modelItems = map.items.filter((item) => KIND_PREFIX[item.kind] !== undefined);
  for (const item of modelItems) {
    const id = itemId(item);
    if (id === undefined) continue;
    const kind =
      item.kind === 'db-function'
        ? 'dbfunction'
        : item.kind === 'trpc-router'
          ? 'router'
          : item.kind === 'mcp-tool'
            ? 'mcptool'
            : item.kind;
    out.push(`  ${kind} ${id} ${quote(item.id)} {`);
    if (item.links.length === 0) out.push('    #unmapped');
    // `kind` は LikeC4 の予約語（where kind is ...）なので metadata のキーに使えない
    const meta = [`inventoryKind ${quote(item.kind)}`];
    if (item.feature) meta.push(`feature ${quote(item.feature)}`);
    if (item.detail) meta.push(`detail ${quote(item.detail)}`);
    out.push(`    metadata { ${meta.join(' ')} }`);
    out.push(`    link ../${item.path}`);
    out.push('  }');
  }
  out.push('');

  // 概念 → 直接対応
  for (const entry of usedConcepts) {
    for (const item of map.byConcept.get(entry.id) ?? []) {
      const id = itemId(item);
      if (id === undefined || !isDirect(item, entry.id)) continue;
      out.push(`  ${conceptId(entry)} -> ${id} 'direct'`);
    }
  }
  // feature → feature（実 import）
  for (const edge of dag.edges) {
    out.push(`  ${likec4Id('f', edge.from)} -> ${likec4Id('f', edge.to)} 'imports'`);
  }
  // feature → router / store（所属）、feature → 関数（.rpc 呼び元）
  for (const item of modelItems) {
    const id = itemId(item);
    if (id === undefined) continue;
    if ((item.kind === 'trpc-router' || item.kind === 'store') && item.feature) {
      out.push(`  ${likec4Id('f', item.feature)} -> ${id} 'owns'`);
    }
    if (item.kind === 'db-function') {
      for (const feature of item.usedBy ?? []) {
        if (dag.features.includes(feature)) {
          out.push(`  ${likec4Id('f', feature)} -> ${id} 'calls'`);
        }
      }
    }
  }
  // table → table（FK）
  const tableIds = new Set(schema.tables.map((table) => likec4Id('t', table.name)));
  for (const table of schema.tables) {
    for (const relationship of table.relationships) {
      const target = likec4Id('t', relationship.referencedTable);
      // 自己参照 FK（oauth_tokens.parent_token_id）は LikeC4 が relation として受け付けない
      if (!tableIds.has(target) || target === likec4Id('t', table.name)) continue;
      out.push(
        `  ${likec4Id('t', table.name)} -> ${target} ${quote(`FK ${relationship.columns.join(', ')}`)}`,
      );
    }
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}

export function renderLikeC4Views({ map, glossary }: LikeC4Sources): string {
  const out = [...HEADER];
  out.push('views {');
  out.push('  view index {');
  out.push("    title 'Dayopt Architecture Map'");
  out.push("    description '概念と feature。概念を選ぶと対応する実装の view へ辿れる'");
  out.push('    include * where kind is concept');
  out.push('    include * where kind is feature');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view features {');
  out.push("    title 'Feature DAG（実 import）'");
  out.push('    include * where kind is feature');
  out.push('    autoLayout TopBottom');
  out.push('  }');
  out.push('  view data {');
  out.push("    title 'DB テーブルと FK'");
  out.push('    include * where kind is table');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view mcp {');
  out.push("    title 'MCP tool と概念'");
  out.push('    include * where kind is mcptool');
  out.push('    include * where kind is concept');
  out.push('    autoLayout LeftRight');
  out.push('  }');
  out.push('  view unmapped {');
  out.push("    title '未マッピング（どの概念からも辿れない要素）'");
  out.push('    include * where tag is #unmapped');
  out.push('    autoLayout TopBottom');
  out.push('  }');
  for (const entry of glossary) {
    const items = map.byConcept.get(entry.id) ?? [];
    if (!items.some((item) => isDirect(item, entry.id) && itemId(item) !== undefined)) continue;
    const id = conceptId(entry);
    out.push(`  view concept_${entry.id.replace(/-/g, '_')} of ${id} {`);
    out.push(`    title ${quote(`${entry.concept}（${entry.id}）`)}`);
    out.push(`    include ${id}, ${id} ->`);
    out.push('    autoLayout LeftRight');
    out.push('  }');
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}
