#!/usr/bin/env tsx

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type AuthEmailTemplate = {
  componentName?: string;
  destination: string;
  kind: 'module' | 'styles' | 'template';
  productAdapters?: readonly {
    expectedOccurrences: number;
    replacement: string;
    search: string;
  }[];
  source: string;
};

type SyncAuthEmailTemplatesOptions = {
  check?: boolean;
  rootDir?: string;
};

const ROOT_DIR = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const GENERATED_HEADER = `// @generated by scripts/tasks/sync-auth-email-templates.ts
// Source of truth: supabase/functions/send-auth-email/. Do not edit this file directly.

`;

export const AUTH_EMAIL_TEMPLATES: readonly AuthEmailTemplate[] = [
  {
    source: 'supabase/functions/send-auth-email/ConfirmEmail.tsx',
    destination: 'apps/product/src/emails/ConfirmEmail.tsx',
    componentName: 'ConfirmEmail',
    kind: 'template',
    productAdapters: [
      {
        expectedOccurrences: 2,
        search: 'ignoreLine: (appUrl: string) =>',
        replacement: 'ignoreLine: (_appUrl: string) =>',
      },
    ],
  },
  {
    source: 'supabase/functions/send-auth-email/EmailChangeEmail.tsx',
    destination: 'apps/product/src/emails/EmailChangeEmail.tsx',
    componentName: 'EmailChangeEmail',
    kind: 'template',
  },
  {
    source: 'supabase/functions/send-auth-email/MagicLinkEmail.tsx',
    destination: 'apps/product/src/emails/MagicLinkEmail.tsx',
    componentName: 'MagicLinkEmail',
    kind: 'template',
  },
  {
    source: 'supabase/functions/send-auth-email/PasswordResetEmail.tsx',
    destination: 'apps/product/src/emails/PasswordResetEmail.tsx',
    componentName: 'PasswordResetEmail',
    kind: 'template',
    productAdapters: [
      {
        expectedOccurrences: 2,
        search: 'securityNote: (appUrl: string) =>',
        replacement: 'securityNote: (_appUrl: string) =>',
      },
    ],
  },
  {
    source: 'supabase/functions/send-auth-email/PasswordChangedEmail.tsx',
    destination: 'apps/product/src/emails/PasswordChangedEmail.tsx',
    componentName: 'PasswordChangedEmail',
    kind: 'template',
  },
  {
    source: 'supabase/functions/send-auth-email/styles.tsx',
    destination: 'apps/product/src/emails/auth-email-styles.generated.ts',
    kind: 'styles',
  },
  {
    source: 'supabase/functions/send-auth-email/subjects.ts',
    destination: 'apps/product/src/emails/auth-email-subjects.generated.ts',
    kind: 'module',
  },
] as const;

function replaceRequired(source: string, search: string, replacement: string): string {
  if (!source.includes(search)) {
    throw new Error(`Expected canonical template fragment was not found: ${search}`);
  }
  return source.replace(search, replacement);
}

function replaceAllRequired(
  source: string,
  search: string,
  replacement: string,
  expectedOccurrences: number,
): string {
  const occurrences = source.split(search).length - 1;
  if (occurrences !== expectedOccurrences) {
    throw new Error(
      `Expected ${expectedOccurrences} canonical template fragments, found ${occurrences}: ${search}`,
    );
  }
  return source.replaceAll(search, replacement);
}

export function generateProductAuthEmailTemplate(
  source: string,
  template: AuthEmailTemplate,
): string {
  let generated = source.trimEnd();

  if (template.kind === 'template') {
    generated = replaceRequired(
      generated,
      "from '@react-email/components';",
      "from 'react-email';",
    );
    generated = replaceRequired(
      generated,
      "from './styles.tsx';",
      "from './auth-email-styles.generated';",
    );
    for (const adapter of template.productAdapters ?? []) {
      generated = replaceAllRequired(
        generated,
        adapter.search,
        adapter.replacement,
        adapter.expectedOccurrences,
      );
    }

    if (!template.componentName) {
      throw new Error(`Missing component name for ${template.source}`);
    }
    generated += `\n\nexport default ${template.componentName};`;
  }

  return `${GENERATED_HEADER}${generated}\n`;
}

export function syncAuthEmailTemplates(options: SyncAuthEmailTemplatesOptions = {}): string[] {
  const rootDir = options.rootDir ?? ROOT_DIR;
  const staleFiles: string[] = [];

  for (const template of AUTH_EMAIL_TEMPLATES) {
    const sourcePath = resolve(rootDir, template.source);
    const destinationPath = resolve(rootDir, template.destination);
    const generated = generateProductAuthEmailTemplate(readFileSync(sourcePath, 'utf8'), template);

    if (options.check) {
      const current = existsSync(destinationPath) ? readFileSync(destinationPath, 'utf8') : '';
      if (current !== generated) staleFiles.push(template.destination);
      continue;
    }

    mkdirSync(dirname(destinationPath), { recursive: true });
    writeFileSync(destinationPath, generated);
  }

  return staleFiles;
}

function isMainModule(): boolean {
  const entryPoint = process.argv[1];
  return entryPoint ? resolve(entryPoint) === fileURLToPath(import.meta.url) : false;
}

if (isMainModule()) {
  const unknownArguments = process.argv.slice(2).filter((argument) => argument !== '--check');
  if (unknownArguments.length > 0) {
    console.error(`Unknown arguments: ${unknownArguments.join(', ')}`);
    process.exit(1);
  }

  const check = process.argv.includes('--check');
  const staleFiles = syncAuthEmailTemplates({ check });

  if (staleFiles.length > 0) {
    console.error('Auth email preview files are out of date:');
    for (const file of staleFiles) console.error(`- ${file}`);
    console.error('Run pnpm auth-email:sync and commit the generated files.');
    process.exit(1);
  }

  console.log(
    check ? 'Auth email preview files are up to date.' : 'Auth email previews generated.',
  );
}
